name: Run Police Email Bot
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install firebase-admin python-dateutil
      - name: Run script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python send_email.py
