name: Run Police Email Bot
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install packages
        run: pip install firebase-admin python-dateutil requests
      - name: Run bot
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python send_email.py
      - name: Commit fingerprints
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add skickade.json
          git commit -m "update fingerprints" || echo "nothing to commit"
          git push
